 -- Definiera villkoren på tabeller 
 
 
-- Primärnycklar 

ALTER TABLE STORES ADD CONSTRAINT STORES_PK PRIMARY KEY (STORENO); 
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEES_PK PRIMARY KEY (EMPLOYEENO);
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PK PRIMARY KEY (MEMBERNO);
ALTER TABLE MOVIES ADD CONSTRAINT MOVIES_PK PRIMARY KEY (MOVIENO);
ALTER TABLE GENRES ADD CONSTRAINT GENRES_PK PRIMARY KEY (MOVIENO, GENRE);
ALTER TABLE MOVIESTAFF ADD CONSTRAINT MOVIESTAFF_PK PRIMARY KEY (IDNO);
ALTER TABLE RESERVATIONS ADD CONSTRAINT RESERVATIONS_PK PRIMARY KEY (MEMBERNO, MOVIENO, REGDATE);
ALTER TABLE RENTALS ADD CONSTRAINT RENTALS_PK PRIMARY KEY (MEMBERNO, MOVIENO, RENTALDATE);
ALTER TABLE WORKED_ON ADD CONSTRAINT WORKED_ON_PK PRIMARY KEY (MOVIENO, IDNO, MOVIEROLE);
ALTER TABLE AVAILABLE_IN ADD CONSTRAINT AVAILABLE_IN_PK PRIMARY KEY (MOVIENO, STORENO);

 -- Främmande nycklar 
 
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_STORE_FK FOREIGN KEY (STORENO) REFERENCES STORES(STORENO); 
ALTER TABLE MEMBERS ADD CONSTRAINT MEM_STORE_FK FOREIGN KEY (STORENO) REFERENCES STORES(STORENO); 
ALTER TABLE GENRES ADD CONSTRAINT GENRES_MOVIES_FK FOREIGN KEY (MOVIENO) REFERENCES MOVIES(MOVIENO); 
ALTER TABLE RESERVATIONS ADD CONSTRAINT RES_MEM_FK FOREIGN KEY (MEMBERNO) REFERENCES MEMBERS(MEMBERNO); 
ALTER TABLE RESERVATIONS ADD CONSTRAINT RES_MOVIE_FK FOREIGN KEY (MOVIENO) REFERENCES MOVIES(MOVIENO); 
ALTER TABLE RENTALS ADD CONSTRAINT RENT_MEM_FK FOREIGN KEY (MEMBERNO) REFERENCES MEMBERS(MEMBERNO); 
ALTER TABLE RENTALS ADD CONSTRAINT RENT_MOVIE_FK FOREIGN KEY (MOVIENO) REFERENCES MOVIES(MOVIENO); 
ALTER TABLE WORKED_ON ADD CONSTRAINT WORKED_MOVIE_FK FOREIGN KEY (MOVIENO) REFERENCES MOVIES(MOVIENO); 
ALTER TABLE WORKED_ON ADD CONSTRAINT WORKED_STAFF_FK FOREIGN KEY (IDNO) REFERENCES MOVIESTAFF(IDNO); 
ALTER TABLE AVAILABLE_IN ADD CONSTRAINT AVAIL_MOVIE_FK FOREIGN KEY (MOVIENO) REFERENCES MOVIES(MOVIENO); 
ALTER TABLE AVAILABLE_IN ADD CONSTRAINT AVAIL_STORE_FK FOREIGN KEY (STORENO) REFERENCES STORES(STORENO); 

/*
 ON DELETE CASCADE   --Bra när du har svag-stark förhållande
 ON DELETE SET NULL  --Bra om du har en FK som inte har "NOT NULL" framför
 ON DELETE SET DEFAULT  --Bra om du har en FK som har ett default värde.
 
 */
 