
DROP TABLE IF EXISTS STORES CASCADE;   -- IF EXISTS är bara för att slippa felmeddelanden Mariadb ger.
DROP TABLE IF EXISTS EMPLOYEES CASCADE;  -- Standard SQL har inte IF EXISTS.
DROP TABLE IF EXISTS MEMBERS CASCADE;
DROP TABLE IF EXISTS MOVIES CASCADE;
DROP TABLE IF EXISTS GENRES CASCADE;
DROP TABLE IF EXISTS MOVIESTAFF CASCADE;
DROP TABLE IF EXISTS RESERVATIONS CASCADE;
DROP TABLE IF EXISTS RENTALS CASCADE;
DROP TABLE IF EXISTS WORKED_ON CASCADE;
DROP TABLE IF EXISTS AVAILABLE_IN CASCADE;
